/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MK40DX256xxx10
package_id: MK40DX256VMD10
mcu_data: ksdk2_0
processor_version: 6.0.0
pin_labels:
- {pin_num: J4, pin_signal: PTE27/UART4_RTS_b/FB_AD21, label: GPIO7, identifier: GPIO7}
- {pin_num: E2, pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FB_TBST_b/FB_CS2_b/FB_BE15_8_b, label: GPIO8, identifier: GPIO8}
- {pin_num: B5, pin_signal: LCD_P39/PTC19/UART3_CTS_b, label: GPIO9, identifier: GPIO9}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B4, peripheral: SPI0, signal: SIN, pin_signal: LCD_P43/PTD3/SPI0_SIN/UART2_TX}
  - {pin_num: C4, peripheral: SPI0, signal: SOUT, pin_signal: LCD_P42/PTD2/LLWU_P13/SPI0_SOUT/UART2_RX}
  - {pin_num: A5, peripheral: SPI0, signal: PCS0_SS, pin_signal: LCD_P40/PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b}
  - {pin_num: D4, peripheral: SPI0, signal: SCK, pin_signal: LCD_P41/ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b}
  - {pin_num: J4, peripheral: GPIOE, signal: 'GPIO, 27', pin_signal: PTE27/UART4_RTS_b/FB_AD21, direction: OUTPUT}
  - {pin_num: E2, peripheral: GPIOE, signal: 'GPIO, 5', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FB_TBST_b/FB_CS2_b/FB_BE15_8_b, direction: OUTPUT}
  - {pin_num: B5, peripheral: GPIOC, signal: 'GPIO, 19', pin_signal: LCD_P39/PTC19/UART3_CTS_b, direction: OUTPUT}
  - {pin_num: M11, peripheral: OSC, signal: XTAL0, pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1}
  - {pin_num: M12, peripheral: OSC, signal: EXTAL0, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t GPIO9_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC19 (pin B5)  */
    GPIO_PinInit(BOARD_INITPINS_GPIO9_GPIO, BOARD_INITPINS_GPIO9_PIN, &GPIO9_config);

    gpio_pin_config_t GPIO8_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE5 (pin E2)  */
    GPIO_PinInit(BOARD_INITPINS_GPIO8_GPIO, BOARD_INITPINS_GPIO8_PIN, &GPIO8_config);

    gpio_pin_config_t GPIO7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE27 (pin J4)  */
    GPIO_PinInit(BOARD_INITPINS_GPIO7_GPIO, BOARD_INITPINS_GPIO7_PIN, &GPIO7_config);

    /* PORTA18 (pin M12) is configured as EXTAL0 */
    PORT_SetPinMux(PORTA, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTA19 (pin M11) is configured as XTAL0 */
    PORT_SetPinMux(PORTA, 19U, kPORT_PinDisabledOrAnalog);

    /* PORTC19 (pin B5) is configured as PTC19 */
    PORT_SetPinMux(BOARD_INITPINS_GPIO9_PORT, BOARD_INITPINS_GPIO9_PIN, kPORT_MuxAsGpio);

    /* PORTD0 (pin A5) is configured as SPI0_PCS0 */
    PORT_SetPinMux(PORTD, 0U, kPORT_MuxAlt2);

    /* PORTD1 (pin D4) is configured as SPI0_SCK */
    PORT_SetPinMux(PORTD, 1U, kPORT_MuxAlt2);

    /* PORTD2 (pin C4) is configured as SPI0_SOUT */
    PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt2);

    /* PORTD3 (pin B4) is configured as SPI0_SIN */
    PORT_SetPinMux(PORTD, 3U, kPORT_MuxAlt2);

    /* PORTE27 (pin J4) is configured as PTE27 */
    PORT_SetPinMux(BOARD_INITPINS_GPIO7_PORT, BOARD_INITPINS_GPIO7_PIN, kPORT_MuxAsGpio);

    /* PORTE5 (pin E2) is configured as PTE5 */
    PORT_SetPinMux(BOARD_INITPINS_GPIO8_PORT, BOARD_INITPINS_GPIO8_PIN, kPORT_MuxAsGpio);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
